/* Import Data from an Excel File */
PROC IMPORT OUT=WORK.DEPRESSION
  DATAFILE="C:\EPIB651\Data\DEPRESSION.csv"
  DBMS=CSV REPLACE;
  GETNAMES=YES;
RUN;

DATA DEPRESSION;
  SET DEPRESSION;
  FEMALE=SEX-1;
  INTERACTION=WP*MC;
RUN;

/* Model Selection with Various Criteria */
PROC REG DATA=DEPRESSION;
  MODEL DEP = AGE FEMALE WP MC INTERACTION / SELECTION=RSQUARE ADJRSQ CP AIC BIC;
RUN;
QUIT;

/* Model Selection by RSQUARE for Each Size */
PROC REG DATA=DEPRESSION;
  MODEL DEP = AGE FEMALE WP MC INTERACTION / SELECTION=RSQUARE ADJRSQ CP AIC BIC BEST=1;
RUN;
QUIT;

/* Forward Selection */
PROC REG DATA=DEPRESSION;
  MODEL DEP = AGE FEMALE WP MC INTERACTION / SELECTION=FORWARD SLENTRY=0.1 DETAILS;
RUN;
QUIT;

/* Backward Elimination */
PROC REG DATA=DEPRESSION;
  MODEL DEP = AGE FEMALE WP MC INTERACTION / SELECTION=BACKWARD SLSTAY=0.1 DETAILS;
RUN;
QUIT;

/* Stepwise Selection */
PROC REG DATA=DEPRESSION;
  MODEL DEP = AGE FEMALE WP MC INTERACTION / SELECTION=STEPWISE SLENTRY=0.1 SLSTAY=0.1 DETAILS;
RUN;
QUIT;
